### ISSUE TITLE
How to binarize dataset with continuous features?

### ISSUE THREAD

**Issue by sabithamanoj** [SanoScience/MISS#1]
I have run the example code for iris dataset and it runs perfect. But how did you create input iris_binary.csv. Could you please let me know how you binarized the dataset? I wanted to use MISS scoring system for my project and dataset contains features that are continuous and need to be binarized.

**Comment by MiHu773** [comment]
Dear @sabithamanoj, Thank you for your interest in our work. Unfortunately, the necessity of "pre-binarization" is the limitation of IP-based methods for building scoring systems. There are multiple strategies that you can use for feature discretization and we followed the approach from the [FD-RiskSLIM](https://www.iccs-meeting.org/archive/iccs2022/papers/133520088.pdf) paper. In our experiments we tested multiple algorithms for binarization (quantiles, kmeans, mdlp etc.). Here is the example of [MDLP discretizer](https://github.com/hlin117/mdlp-discretization) which you can use.

**Comment by sabithamanoj** [comment]
Thank you very much for the information!
